var annotated_dup =
[
    [ "plywoot", null, [
      [ "detail", null, [
        [ "AsciiParserPolicy", "classplywoot_1_1detail_1_1AsciiParserPolicy.html", "classplywoot_1_1detail_1_1AsciiParserPolicy" ],
        [ "AsciiWriterPolicy", "classplywoot_1_1detail_1_1AsciiWriterPolicy.html", "classplywoot_1_1detail_1_1AsciiWriterPolicy" ],
        [ "BigEndian", "structplywoot_1_1detail_1_1BigEndian.html", null ],
        [ "BinaryParserPolicy", "classplywoot_1_1detail_1_1BinaryParserPolicy.html", "classplywoot_1_1detail_1_1BinaryParserPolicy" ],
        [ "BinaryWriterPolicy", "classplywoot_1_1detail_1_1BinaryWriterPolicy.html", "classplywoot_1_1detail_1_1BinaryWriterPolicy" ],
        [ "BufferedIStream", "classplywoot_1_1detail_1_1BufferedIStream.html", "classplywoot_1_1detail_1_1BufferedIStream" ],
        [ "BufferedOStream", "classplywoot_1_1detail_1_1BufferedOStream.html", "classplywoot_1_1detail_1_1BufferedOStream" ],
        [ "HeaderScanner", "classplywoot_1_1detail_1_1HeaderScanner.html", "classplywoot_1_1detail_1_1HeaderScanner" ],
        [ "IsList", "structplywoot_1_1detail_1_1IsList.html", null ],
        [ "IsList< reflect::Array< T, N > >", "structplywoot_1_1detail_1_1IsList_3_01reflect_1_1Array_3_01T_00_01N_01_4_01_4.html", null ],
        [ "IsList< reflect::Type< T > >", "structplywoot_1_1detail_1_1IsList_3_01reflect_1_1Type_3_01T_01_4_01_4.html", null ],
        [ "IsList< std::vector< T > >", "structplywoot_1_1detail_1_1IsList_3_01std_1_1vector_3_01T_01_4_01_4.html", null ],
        [ "IsMemcpyable", "structplywoot_1_1detail_1_1IsMemcpyable.html", null ],
        [ "IsMemcpyable< reflect::Array< T, N > >", "structplywoot_1_1detail_1_1IsMemcpyable_3_01reflect_1_1Array_3_01T_00_01N_01_4_01_4.html", null ],
        [ "IsMemcpyable< reflect::Pack< T, N > >", "structplywoot_1_1detail_1_1IsMemcpyable_3_01reflect_1_1Pack_3_01T_00_01N_01_4_01_4.html", null ],
        [ "IsPack", "structplywoot_1_1detail_1_1IsPack.html", null ],
        [ "IsPack< reflect::Pack< T, N > >", "structplywoot_1_1detail_1_1IsPack_3_01reflect_1_1Pack_3_01T_00_01N_01_4_01_4.html", null ],
        [ "LittleEndian", "structplywoot_1_1detail_1_1LittleEndian.html", null ],
        [ "NumProperties", "structplywoot_1_1detail_1_1NumProperties.html", null ],
        [ "NumProperties< reflect::Array< T, N > >", "structplywoot_1_1detail_1_1NumProperties_3_01reflect_1_1Array_3_01T_00_01N_01_4_01_4.html", null ],
        [ "NumProperties< reflect::Pack< T, N > >", "structplywoot_1_1detail_1_1NumProperties_3_01reflect_1_1Pack_3_01T_00_01N_01_4_01_4.html", null ],
        [ "NumProperties< T >", "structplywoot_1_1detail_1_1NumProperties_3_01T_01_4.html", null ],
        [ "NumProperties< T, Ts... >", "structplywoot_1_1detail_1_1NumProperties_3_01T_00_01Ts_8_8_8_01_4.html", null ],
        [ "Parser", "classplywoot_1_1detail_1_1Parser.html", "classplywoot_1_1detail_1_1Parser" ],
        [ "ParserVariant", "classplywoot_1_1detail_1_1ParserVariant.html", null ],
        [ "SizeOf", "structplywoot_1_1detail_1_1SizeOf.html", null ],
        [ "SizeOf< reflect::Array< T, N > >", "structplywoot_1_1detail_1_1SizeOf_3_01reflect_1_1Array_3_01T_00_01N_01_4_01_4.html", null ],
        [ "SizeOf< reflect::Pack< T, N > >", "structplywoot_1_1detail_1_1SizeOf_3_01reflect_1_1Pack_3_01T_00_01N_01_4_01_4.html", null ],
        [ "SizeOf< T >", "structplywoot_1_1detail_1_1SizeOf_3_01T_01_4.html", null ],
        [ "Writer", "classplywoot_1_1detail_1_1Writer.html", "classplywoot_1_1detail_1_1Writer" ],
        [ "WriterVariant", "classplywoot_1_1detail_1_1WriterVariant.html", null ]
      ] ],
      [ "reflect", null, [
        [ "Array", "structplywoot_1_1reflect_1_1Array.html", null ],
        [ "Layout", "classplywoot_1_1reflect_1_1Layout.html", "classplywoot_1_1reflect_1_1Layout" ],
        [ "Pack", "structplywoot_1_1reflect_1_1Pack.html", null ],
        [ "Skip", "structplywoot_1_1reflect_1_1Skip.html", null ],
        [ "Stride", "structplywoot_1_1reflect_1_1Stride.html", null ],
        [ "Type", "structplywoot_1_1reflect_1_1Type.html", null ],
        [ "Type< T, typename Void< typename T::DestT >::type >", "structplywoot_1_1reflect_1_1Type_3_01T_00_01typename_01Void_3_01typename_01T_1_1DestT_01_4_1_1type_01_4.html", null ],
        [ "Void", "structplywoot_1_1reflect_1_1Void.html", null ]
      ] ],
      [ "Comment", "structplywoot_1_1Comment.html", null ],
      [ "Exception", "classplywoot_1_1Exception.html", null ],
      [ "HeaderParserException", "structplywoot_1_1HeaderParserException.html", null ],
      [ "HeaderScannerException", "structplywoot_1_1HeaderScannerException.html", null ],
      [ "InvalidFormat", "structplywoot_1_1InvalidFormat.html", null ],
      [ "InvalidInputStream", "structplywoot_1_1InvalidInputStream.html", null ],
      [ "IStream", "classplywoot_1_1IStream.html", "classplywoot_1_1IStream" ],
      [ "OStream", "classplywoot_1_1OStream.html", "classplywoot_1_1OStream" ],
      [ "ParserException", "structplywoot_1_1ParserException.html", null ],
      [ "PlyElement", "structplywoot_1_1PlyElement.html", "structplywoot_1_1PlyElement" ],
      [ "PlyElementData", "classplywoot_1_1PlyElementData.html", "classplywoot_1_1PlyElementData" ],
      [ "PlyProperty", "structplywoot_1_1PlyProperty.html", "structplywoot_1_1PlyProperty" ],
      [ "UnexpectedEof", "structplywoot_1_1UnexpectedEof.html", null ],
      [ "UnexpectedToken", "structplywoot_1_1UnexpectedToken.html", null ]
    ] ]
];